name: maven-verify

on:
  push:
    branches:
      - main
      - master

env:
  ODLNEXUSPROXY: ${{ vars.NEXUSPROXY }}
  NEXUSPROXY: ${{ vars.NEXUSPROXY }}
jobs:

    maven-verify:    
        uses: lfit/releng-reusable-workflows/.github/workflows/compose-maven-verify.yaml@main
        with:
            GERRIT_BRANCH: "main"
            GERRIT_CHANGE_ID: "your_change_id"
            GERRIT_CHANGE_NUMBER: "your_change_number"
            GERRIT_CHANGE_URL: "https://git.opendaylight.org/gerrit/aaa"
            GERRIT_EVENT_TYPE: "change-merged"
            GERRIT_PATCHSET_NUMBER: "1"
            GERRIT_PATCHSET_REVISION: "your_revision_sha"
            GERRIT_PROJECT: "https://git.opendaylight.org/gerrit/aaa"
            GERRIT_REFSPEC: "refs/changes/1/1/1"
            JDK_VERSION: "17"
            MVN_VERSION: "3.8.3"
            MVN_PHASES: "clean,install"
            MVN_POM_FILE: "pom.xml"
            MVN_PROFILES: ""
            ENV_VARS: ${{ toJSON(vars) }}
            ENV_SECRETS: "{}"
